---
- name: Install puppet-release
  yum:
    name: https://yum.puppetlabs.com/puppet-release-el-7.noarch.rpm
    state: present
  become: true

- name: Install puppet-agent
  yum:
    name: puppet-agent
    state: present
    update_cache: true
  become: true
