---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: centos9
    image: quay.io/centos/centos:stream9
  - name: ubuntu2204
    image: ubuntu:22.04
  - name: ubuntu2404
    image: ubuntu:24.04
provisioner:
  name: ansible
  config_options:
    defaults:
      callbacks_enabled: profile_tasks
      inject_facts_as_vars: false
  inventory:
    host_vars:
      centos9:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu2204:
        ansible_python_interpreter: /usr/bin/python3
      ubuntu2404:
        ansible_python_interpreter: /usr/bin/python3
scenario:
  name: default
  test_sequence:
    - destroy
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - destroy
verifier:
  name: ansible
