---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint tasks/*.yml
platforms:
  - name: centos7
    image: centos:7
  - name: ubuntu1604
    image: ubuntu:16.04
  - name: ubuntu1804
    image: ubuntu:18.04
provisioner:
  name: ansible
scenario:
  name: default
verifier:
  name: testinfra
